#Import Libraries
from sklearn.model_selection import KFold
#----------------------------------------------------

#KFold Splitting data

kf = KFold(n_splits=4, random_state=44, shuffle =True)

#KFold Data
for train_index, test_index in kf.split(X):
    print('Train Data is : \n', train_index)
    print('Test Data is  : \n', test_index)
    print('-------------------------------')
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train Shape is  ' , X_train.shape)
    print('X_test Shape is  ' , X_test.shape)
    print('y_train Shape is  ' ,y_train.shape)
    print('y_test Shape is  ' , y_test.shape)
    print('========================================')

In [1]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([11, 22, 33, 44])

In [2]:
nn = 2
#nn=3
#nn=4

kf = KFold(n_splits=nn)
kf.get_n_splits(X)
KFold(n_splits=nn, random_state=None, shuffle=False)

KFold(n_splits=2, random_state=None, shuffle=False)

In [3]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)

TRAIN: [2 3] TEST: [0 1]
X_train 
 [[5 6]
 [7 8]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [33 44]
y_test 
 [11 22]
TRAIN: [0 1] TEST: [2 3]
X_train 
 [[1 2]
 [3 4]]
X_test 
 [[5 6]
 [7 8]]
y_train 
 [11 22]
y_test 
 [33 44]
